<Project>
    <PropertyGroup>
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    </PropertyGroup>

    <ItemGroup>
        <PackageVersion Include="Avalonia" Version="11.0.11" />
        <PackageVersion Include="Avalonia.Browser" Version="11.0.11" />
        <PackageVersion Include="Avalonia.Controls.DataGrid" Version="11.0.11" />
        <PackageVersion Include="Avalonia.Desktop" Version="11.0.11" />
        <PackageVersion Include="Avalonia.Diagnostics" Version="11.0.11" Condition="'$(Configuration)' == 'Debug'" />
        <PackageVersion Include="Avalonia.Fonts.Inter" Version="11.0.11" />
        <PackageVersion Include="Avalonia.Headless.NUnit" Version="11.0.11" />
        <PackageVersion Include="Avalonia.ReactiveUI" Version="11.0.11" />
        <PackageVersion Include="Avalonia.Themes.Fluent" Version="11.0.11" />
        <PackageVersion Include="coverlet.collector" Version="6.0.2" />
        <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
        <PackageVersion Include="Microsoft.Extensions.Logging" Version="8.0.0" />
        <PackageVersion Include="Microsoft.Extensions.Logging.Console" Version="8.0.0" />
        <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.10.0" />
        <PackageVersion Include="Mapsui.Avalonia" Version="4.1.7" />
        <PackageVersion Include="Moq" Version="4.20.70" />
        <PackageVersion Include="NUnit" Version="4.1.0" />
        <PackageVersion Include="NUnit.Analyzers" Version="4.2.0" />
        <PackageVersion Include="NUnit3TestAdapter" Version="4.5.0" />
        <PackageVersion Include="ReactiveUI.Fody" Version="19.5.41" />
    </ItemGroup>
</Project>
