<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFrameworks>net6.0;net7.0;net8.0</TargetFrameworks>
        <OutputType>WinExe</OutputType>
        <Nullable>enable</Nullable>

        <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia.Desktop" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\ImeSense.GeneoGraph\ImeSense.GeneoGraph.csproj" />
    </ItemGroup>
</Project>
