<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFrameworks>net6.0;net7.0;net8.0</TargetFrameworks>
        <OutputType>Library</OutputType>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\**" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="11.0.11" />
        <PackageReference Include="Avalonia.Controls.DataGrid" Version="11.0.11" />
        <PackageReference Include="Avalonia.Diagnostics" Version="11.0.11" Condition="'$(Configuration)' == 'Debug'" />
        <PackageReference Include="Avalonia.Fonts.Inter" Version="11.0.11" />
        <PackageReference Include="Avalonia.ReactiveUI" Version="11.0.11" />
        <PackageReference Include="Avalonia.Themes.Fluent" Version="11.0.11" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
        <PackageReference Include="Microsoft.Extensions.Logging" Version="8.0.0" />
        <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="8.0.0" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="ImeSense.GeneoGraph.Tests" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\ImeSense.GeneoGraph.Themes\ImeSense.GeneoGraph.Themes.csproj" />
    </ItemGroup>
</Project>
