<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFrameworks>net6.0;net7.0;net8.0</TargetFrameworks>
        <OutputType>Library</OutputType>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\**" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" />
        <PackageReference Include="Avalonia.Controls.DataGrid" />
        <PackageReference Include="Avalonia.Diagnostics">
            <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
            <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Avalonia.Fonts.Inter" />
        <PackageReference Include="Avalonia.ReactiveUI" />
        <PackageReference Include="Avalonia.Themes.Fluent" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
        <PackageReference Include="Microsoft.Extensions.Logging" />
        <PackageReference Include="Microsoft.Extensions.Logging.Console" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="ImeSense.GeneoGraph.Tests" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\ImeSense.GeneoGraph.Themes\ImeSense.GeneoGraph.Themes.csproj" />
    </ItemGroup>
</Project>
