<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFrameworks>net7.0-macos;net8.0-macos</TargetFrameworks>
        <OutputType>Exe</OutputType>
        <Nullable>enable</Nullable>
        <BuiltInComInteropSupport>true</BuiltInComInteropSupport>

        <OutputPath>$(BaseOutputPath)\$(Configuration)\$(TargetFramework)</OutputPath>
        <UseAppHost>true</UseAppHost>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <SupportedOSPlatformVersion>13.0</SupportedOSPlatformVersion>
    </PropertyGroup>

    <ItemGroup>
        <None Include="Info.plist" />
        <None Include="Entitlements.plist" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia.Desktop" Version="11.0.10" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\ImeSense.GeneoGraph\ImeSense.GeneoGraph.csproj" />
    </ItemGroup>
</Project>
