<Project Sdk="Microsoft.NET.Sdk.WebAssembly">
    <PropertyGroup>
        <TargetFrameworks>net8.0-browser</TargetFrameworks>
        <OutputType>Exe</OutputType>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia.Browser" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\ImeSense.GeneoGraph\ImeSense.GeneoGraph.csproj" />
    </ItemGroup>
</Project>
