<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFrameworks>net6.0;net7.0;net8.0</TargetFrameworks>
        <OutputType>Library</OutputType>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <AvaloniaResource Include="Controls\**" />
        <AvaloniaResource Include="Fonts\**" />
        <AvaloniaResource Include="Palettes\**" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" />
    </ItemGroup>

    <Target Name="PreBuildCopy" BeforeTargets="BeforeBuild">
        <Copy
            SourceFiles="$(ProjectDir)\dep\Inter\4.1\InterVariable.ttf"
            DestinationFiles="$(MSBuildThisFileDirectory)\Fonts\InterVariable.ttf"
            Condition="Exists('$(MSBuildThisFileDirectory)\Fonts\InterVariable.ttf')" />
        <Copy
            SourceFiles="$(ProjectDir)\dep\Roboto\3.010\Roboto_v3.010\hinted\Roboto[ital,wdth,wght].ttf"
            DestinationFiles="$(MSBuildThisFileDirectory)\Fonts\Roboto.ttf"
            Condition="Exists('$(MSBuildThisFileDirectory)\Fonts\Roboto.ttf')" />
    </Target>
</Project>
