name: 'Build application'

on:
  push:
    branches:
      - '**'
    paths:
      - '.github/workflows/**'
      - 'src/**'
      - '*.sln'
      - '*.props'
  pull_request:
    branches:
      - '**'
    paths:
      - '.github/workflows/**'
      - 'src/**'
      - '*.sln'
      - '*.props'

defaults:
  run:
    shell: pwsh

jobs:
  build-application:
    name: 'Build application'

    strategy:
      matrix:
        system:
          - windows-2022
          - ubuntu-22.04
          - macos-14
        config:
          - Debug
          - Release

    runs-on: ${{ matrix.system }}

    env:
      Solution: GeneoGraph.slnf

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Cache workloads (Windows)
        uses: actions/cache@v4
        if: ${{ contains(matrix.system, 'windows') }}
        with:
          key: GeneoGraph-Workloads-${{ runner.os }}-
          restore-keys: |
            GeneoGraph-Workloads-${{ runner.os }}-
          path: |
            C:\ProgramData\dotnet\workloads\**\*.msi

      - name: Cache workloads (Linux)
        uses: actions/cache@v4
        if: ${{ contains(matrix.system, 'ubuntu') }}
        with:
          key: GeneoGraph-Workloads-${{ runner.os }}-
          restore-keys: |
            GeneoGraph-Workloads-${{ runner.os }}-
          path: |
            /usr/share/dotnet/packs/**/*.nupkg

      - name: Cache workloads (macOS)
        uses: actions/cache@v4
        if: ${{ contains(matrix.system, 'macos') }}
        with:
          key: GeneoGraph-Workloads-${{ runner.os }}-
          restore-keys: |
            GeneoGraph-Workloads-${{ runner.os }}-
          path: |
            ~/.dotnet/packs/**/*.nupkg

      - name: Install workloads
        run: |
          dotnet workload install `
            wasm-tools `
            wasm-tools-net7 `
            macos

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          key: GeneoGraph-NuGet-${{ runner.os }}-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            GeneoGraph-NuGet-${{ runner.os }}-${{ hashFiles('**/packages.lock.json') }}
            GeneoGraph-NuGet-${{ runner.os }}-
            GeneoGraph-NuGet-
          path: |
            ~/.nuget/packages

      - name: Restore dependencies
        run: |
          dotnet restore $env:Solution `
            --locked-mode

      - name: Build application
        run: |
          dotnet build $env:Solution `
            --configuration ${{ matrix.config }} `
            --no-restore

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: geneograph-${{ matrix.system }}-${{ matrix.config }}-${{ github.sha }}
          path: bin/${{ matrix.config }}/
