name: 'Build application'

on:
  push:
    branches:
      - '**'
    paths:
      - '.github/workflows/**'
      - 'src/**'
      - '*.sln'
      - '*.props'
  pull_request:
    branches:
      - '**'
    paths:
      - '.github/workflows/**'
      - 'src/**'
      - '*.sln'
      - '*.props'

defaults:
  run:
    shell: pwsh

jobs:
  build-app:
    name: 'Build'

    strategy:
      matrix:
        system:
          - windows-2022
        config:
          - Debug
          - Release

    runs-on: ${{ matrix.system }}

    env:
      Solution: GeneoGraph.sln

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v3.0.3
        with:
          dotnet-version: '7.0.x'

      - name: Restore workloads
        run: |
          dotnet workload restore

      - name: Restore dependencies
        run: |
          dotnet restore $env:Solution

      - name: Build application
        run: |
          dotnet build $env:Project `
            --configuration ${{ matrix.config }} `
            --no-restore

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: bin-${{ matrix.config }}-${{ github.sha }}
          path: bin/${{ matrix.config }}/
